[GLOBAL]
pants_version = "2.7.0"
backend_packages = ["pants.backend.python"]


 [anonymous-telemetry]
 enabled = false

[python-infer]
string_imports = true


[source]
marker_filenames = ["pyproject.toml", "setup.py", "tox.ini", "setup.cfg"]
